### ISSUE TITLE
Request to add multiple articles at once

### ISSUE THREAD

**Issue by a-anoop** [nokibsarkar/bot-wikifolklore-issues#12]
I am requesting a option for bulk adding/importing articles and page creators from fountain tool to campwiz tool , since participants on knwiki are using only fountain tool https://fountain.toolforge.org/editathons/kn-faf2024

https://tools.wikilovesfolklore.org/campwiz/campaign/48

**Comment by nokibsarkar** [comment]
The `bulk import` action is done from the backend by the developer.
- [x] https://fountain.toolforge.org/editathons/kn-faf2024 &rarr; https://tools.wikilovesfolklore.org/campwiz/campaign/48
